name: "Juju JAAS Smoke Test"
on:
  push:
    branches: ["[0-9].[0-9]+", "[0-9].[0-9]+.[0-9]+"]
  pull_request:
    branches-ignore: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    name: JAAS Smoke Test
    runs-on: [self-hosted, linux, x64, aws, large]
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Install Dependencies
        shell: bash
        run: |
          set -euxo pipefail
          echo "/snap/bin" >> $GITHUB_PATH
          sudo DEBIAN_FRONTEND=noninteractive apt install -y expect

      - name: Checkout juju
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup env
        shell: bash
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install local Juju
        shell: bash
        run: |
          make go-install
          
      - name: Start JIMM, bootstrap a Juju controller and add it to JIMM.
        uses: canonical/jimm/.github/actions/test-server@v3
        id: jaas
        with:
          jimm-version: v3.3.8
          ghcr-pat: ${{ secrets.GITHUB_TOKEN }}
          dump-logs: true
          use-charmed-k8s-action: "false"
      
      - name: Create a model, deploy an application and run juju status
        run: |
          juju add-model foo && \
          juju deploy haproxy && \
          sleep 5 && \
          juju status
